apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-sjm-18-python-19-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-sjm-18-python-19-1 
  name: test-sjm-18-python-19-1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-sjm-18-python-19-1 
